INSERT INTO users (name, email, city, preferred_category, budget) VALUES
('Aman', 'aman@email.com', 'Delhi', 'Electronics', 3000),
('Priya', 'priya@email.com', 'Mumbai', 'Fashion', 15000),
('Rohit', 'rohit@email.com', 'Jaipur', 'Accessories', 5000);

INSERT INTO products (product_name, brand, category, description, average_rating, stock_quantity) VALUES
('Samsung Galaxy M14', 'Samsung', 'Electronics', '5G smartphone with large battery and fast performance', 4.4, 18),
('Realme Narzo 60', 'Realme', 'Electronics', 'Budget friendly 5G smartphone with AMOLED display', 4.3, 22),
('Redmi Note 13', 'Xiaomi', 'Electronics', 'Smooth smartphone with strong camera and bright display', 4.5, 15),
('Noise Smart Watch', 'Noise', 'Wearables', 'Affordable smartwatch with fitness tracking features', 4.1, 25),
('Fire-Boltt Ninja Call', 'Fire-Boltt', 'Wearables', 'Calling smartwatch with health tracking support', 4.0, 19),
('Puma Running Shoes', 'Puma', 'Fashion', 'Comfortable running shoes for daily training', 4.3, 14),
('Levis Denim Jacket', 'Levis', 'Fashion', 'Classic denim jacket for stylish casual wear', 4.6, 11),
('Nike Sports T-Shirt', 'Nike', 'Fashion', 'Breathable sports t-shirt for workouts and daily wear', 4.4, 26),
('HP Wireless Mouse', 'HP', 'Accessories', 'Compact wireless mouse for home and office use', 4.2, 30),
('Logitech K380 Keyboard', 'Logitech', 'Accessories', 'Portable multi-device Bluetooth keyboard', 4.7, 14),
('Boat Rockerz 450', 'Boat', 'Electronics', 'Wireless headphones with deep bass sound', 4.0, 20),
('JBL Go 3', 'JBL', 'Electronics', 'Portable Bluetooth speaker with rich audio output', 4.6, 12),
('Milton Water Bottle', 'Milton', 'Home', 'Durable water bottle for regular daily use', 4.5, 40),
('Prestige Induction Cooktop', 'Prestige', 'Home', 'Compact induction cooktop with preset cooking menus', 4.3, 13),
('The Alchemist', 'HarperCollins', 'Books', 'Bestselling inspirational fiction title', 4.8, 44),
('Atomic Habits', 'Penguin', 'Books', 'Popular self-improvement book on habit building', 4.9, 38);

INSERT INTO platform_prices (
    product_id,
    platform_name,
    price,
    delivery_charge,
    discount_percent,
    availability_status,
    seller_name,
    product_url
) VALUES
(1, 'Amazon', 12999, 40, 8, 'In Stock', 'Amazon Retail', 'https://example.com/amazon-galaxy-m14'),
(1, 'Flipkart', 12499, 0, 10, 'In Stock', 'Flipkart Seller', 'https://example.com/flipkart-galaxy-m14'),
(1, 'Croma', 13150, 60, 5, 'Limited Stock', 'Croma Store', 'https://example.com/croma-galaxy-m14'),
(2, 'Amazon', 15999, 50, 7, 'In Stock', 'Amazon Retail', 'https://example.com/amazon-realme-narzo'),
(2, 'Flipkart', 15499, 0, 10, 'In Stock', 'Flipkart Seller', 'https://example.com/flipkart-realme-narzo'),
(2, 'Reliance', 16100, 45, 6, 'In Stock', 'Reliance Digital', 'https://example.com/reliance-realme-narzo'),
(3, 'Amazon', 17499, 40, 9, 'In Stock', 'Amazon Retail', 'https://example.com/amazon-redmi-note-13'),
(3, 'Flipkart', 16999, 0, 11, 'In Stock', 'Flipkart Seller', 'https://example.com/flipkart-redmi-note-13'),
(3, 'Croma', 17650, 70, 4, 'Limited Stock', 'Croma Store', 'https://example.com/croma-redmi-note-13'),
(4, 'Amazon', 2499, 40, 12, 'In Stock', 'Amazon Retail', 'https://example.com/amazon-noise-watch'),
(4, 'Flipkart', 2299, 0, 15, 'In Stock', 'Smart Hub', 'https://example.com/flipkart-noise-watch'),
(4, 'Myntra', 2599, 50, 9, 'In Stock', 'Myntra Fashion', 'https://example.com/myntra-noise-watch'),
(5, 'Amazon', 1999, 30, 16, 'In Stock', 'Amazon Retail', 'https://example.com/amazon-fireboltt'),
(5, 'Flipkart', 1899, 0, 18, 'In Stock', 'Smart Hub', 'https://example.com/flipkart-fireboltt'),
(5, 'Myntra', 2149, 40, 10, 'In Stock', 'Myntra Fashion', 'https://example.com/myntra-fireboltt'),
(6, 'Amazon', 3199, 70, 10, 'In Stock', 'Amazon Retail', 'https://example.com/amazon-puma-shoes'),
(6, 'Flipkart', 2999, 40, 14, 'In Stock', 'Shoe Plaza', 'https://example.com/flipkart-puma-shoes'),
(6, 'Myntra', 2899, 0, 18, 'In Stock', 'Puma Official', 'https://example.com/myntra-puma-shoes'),
(7, 'Amazon', 3499, 40, 10, 'In Stock', 'Amazon Retail', 'https://example.com/amazon-levis-jacket'),
(7, 'Myntra', 3299, 0, 16, 'In Stock', 'Levis Official', 'https://example.com/myntra-levis-jacket'),
(7, 'Ajio', 3399, 20, 14, 'In Stock', 'Ajio Fashion', 'https://example.com/ajio-levis-jacket'),
(8, 'Amazon', 1499, 30, 9, 'In Stock', 'Amazon Retail', 'https://example.com/amazon-nike-tee'),
(8, 'Myntra', 1399, 0, 14, 'In Stock', 'Nike Store', 'https://example.com/myntra-nike-tee'),
(8, 'Ajio', 1449, 20, 12, 'In Stock', 'Ajio Fashion', 'https://example.com/ajio-nike-tee'),
(9, 'Amazon', 799, 30, 6, 'In Stock', 'HP Store', 'https://example.com/amazon-hp-mouse'),
(9, 'Flipkart', 749, 0, 8, 'In Stock', 'Tech Deals', 'https://example.com/flipkart-hp-mouse'),
(9, 'Reliance', 820, 20, 5, 'In Stock', 'Reliance Digital', 'https://example.com/reliance-hp-mouse'),
(10, 'Amazon', 2999, 0, 10, 'In Stock', 'Logitech Official', 'https://example.com/amazon-logitech-k380'),
(10, 'Flipkart', 3099, 0, 7, 'In Stock', 'Tech Deals', 'https://example.com/flipkart-logitech-k380'),
(10, 'Croma', 3249, 40, 5, 'In Stock', 'Croma Store', 'https://example.com/croma-logitech-k380'),
(11, 'Amazon', 1499, 20, 11, 'In Stock', 'Boat Official', 'https://example.com/amazon-boat-rockerz'),
(11, 'Flipkart', 1399, 0, 13, 'In Stock', 'Audio World', 'https://example.com/flipkart-boat-rockerz'),
(11, 'Croma', 1599, 35, 7, 'Limited Stock', 'Croma Store', 'https://example.com/croma-boat-rockerz'),
(12, 'Amazon', 2799, 0, 12, 'In Stock', 'JBL Official', 'https://example.com/amazon-jbl-go3'),
(12, 'Flipkart', 2899, 0, 8, 'In Stock', 'Audio World', 'https://example.com/flipkart-jbl-go3'),
(12, 'Reliance', 2949, 30, 7, 'In Stock', 'Reliance Digital', 'https://example.com/reliance-jbl-go3'),
(13, 'Amazon', 599, 25, 4, 'In Stock', 'Home Essentials', 'https://example.com/amazon-milton-bottle'),
(13, 'Flipkart', 549, 0, 6, 'In Stock', 'Kitchen Mart', 'https://example.com/flipkart-milton-bottle'),
(13, 'JioMart', 575, 15, 5, 'In Stock', 'JioMart Seller', 'https://example.com/jiomart-milton-bottle'),
(14, 'Amazon', 2499, 0, 15, 'In Stock', 'Prestige Official', 'https://example.com/amazon-prestige-induction'),
(14, 'Flipkart', 2399, 0, 17, 'In Stock', 'Kitchen Mart', 'https://example.com/flipkart-prestige-induction'),
(14, 'Reliance', 2549, 30, 11, 'In Stock', 'Reliance Digital', 'https://example.com/reliance-prestige-induction'),
(15, 'Amazon', 299, 0, 20, 'In Stock', 'Books World', 'https://example.com/amazon-the-alchemist'),
(15, 'Flipkart', 289, 0, 22, 'In Stock', 'Book Store', 'https://example.com/flipkart-the-alchemist'),
(15, 'Reliance', 320, 20, 14, 'In Stock', 'Reliance Books', 'https://example.com/reliance-the-alchemist'),
(16, 'Amazon', 499, 0, 18, 'In Stock', 'Books World', 'https://example.com/amazon-atomic-habits'),
(16, 'Flipkart', 479, 0, 21, 'In Stock', 'Book Store', 'https://example.com/flipkart-atomic-habits'),
(16, 'JioMart', 525, 15, 12, 'In Stock', 'JioMart Seller', 'https://example.com/jiomart-atomic-habits');
